server:
  port: 8080
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/2lusy/properties.git
          username: 
          password: 
  application:
    name: microservice-config-server-eureka

eureka:
  client:
    serviceUrl:
      defaultZone: http://user:password123@localhost:8761/eureka
  instance:
    prefer-ip-address: true